### ISSUE TITLE
gRPC error after updating Memos - failed to create memo

### ISSUE THREAD

**Issue by redrabbitrob** [usememos/telegram-integration#106]
### Describe the bug

Hi,

After updating Memos to the latest version, I'm encountering an error when trying to create a memo using Memogram:

2025/02/05 22:41:38 ERROR failed to create memo err="rpc error: code = Internal desc = grpc: error unmarshalling request: proto:\u00a0cannot parse invalid wire-format data"  

Has anybody the same issue?

### Steps to reproduce

Steps to reproduce:
Update Memos to the latest version
Use Memogram via telegram to create a new memo
Observe the error

### The version of Memos you're using

0.24.0

### Screenshots or additional context

Memogram should successfully create a new memo without any errors.

**Comment by boojack** [comment]
Fixed with https://github.com/usememos/telegram-integration/commit/99e8b304ac788a071eea636068a9bab50f7b830f. You can upgrade memogram to `v0.2.0` later.

**Comment by dwong33** [comment]
The problem persists after updating to `v0.2.0`.

Error log:
```
2025/02/06 09:41:41 INFO Memogram started
2025/02/06 09:41:41 INFO workspace profile profile="owner:\"users/1\" version:\"0.24.0\" mode:\"prod\""
2025/02/06 09:42:00 ERROR failed to create memo err="rpc error: code = Internal desc = grpc: error unmarshalling request: proto:\u00a0cannot parse invalid wire-format data"
```

**Comment by redrabbitrob** [comment]
for me, sadly still not fixed

**Comment by Baoyx007** [comment]
not fixed

**Comment by CY-Christin** [comment]
My memo runs with docker

```
CONTAINER ID   IMAGE                         COMMAND                  CREATED         STATUS        PORTS                                                 NAMES
62b4688a56cd   neosmemo/memos:stable         "./entrypoint.sh ./m…"   3 days ago      Up 3 days     0.0.0.0:5230->5230/tcp, :::5230->5230/tcp             memos
```
the port is 0.0.0.0:5230, so I change the .env file to `SERVER_ADDR=dns:0.0.0.0:5230`, and it works.
